import { Pipe, PipeTransform } from '@angular/core';
import { LanguageService } from '../services/language.service';

type Lang = 'it' | 'en';

const FALLBACK: Record<Lang, Record<string, string>> = {
  it: {
    'common.search': 'Cerca',
    'common.new': 'Nuovo',
    'common.filters': 'Filtri',
    'common.refresh': 'Aggiorna',
    'common.of': 'di',
    'common.prev': 'Precedente',
    'common.next': 'Successiva',
    'common.close': 'Chiudi',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.proceed': 'Procedi',

    'filters.errorLoading': 'Errore nel caricamento dei filtri',
    'filters.cities': 'Città',
    'filters.searchCity': 'Cerca città',
    'filters.categories': 'Categoria',
    'filters.searchCategory': 'Cerca categoria',
    'filters.status': 'Stato',
    'filters.searchStatus': 'Cerca stato',
    'filters.clear': 'Pulisci',
    'filters.apply': 'Applica',

    'form.name': 'Nome',
    'form.city': 'Città',
    'form.category': 'Categoria',
    'form.assigned': 'Assegnato',
    'form.status': 'Status',
    'form.follow1': 'Follow up 1',
    'form.follow2': 'Follow up 2',
    'form.site': 'Sito',
    'form.email': 'Email',
    'form.phone': 'Telefono',
    'form.moreContacts': 'Contatti aggiuntivi',
    'form.email2': 'Email 2',
    'form.phone2': 'Telefono 2',
    'form.email3': 'Email 3',
    'form.phone3': 'Telefono 3',
    'form.notes': 'Note',
    'form.required': 'Obbligatorio',
    'form.fillRequired': 'Compila i campi obbligatori:',

    'details.title': 'Dettagli cliente',
    'confirm.delete.title': 'Confermi l\'eliminazione?',
    'confirm.delete.warning': 'Questa azione non è reversibile.',
    'confirm.site.title': 'Aprire il link esterno?',
    'confirm.site.opening': 'Stai per aprire:',
    'confirm.save.title': 'Confermi le modifiche?',
    'confirm.save.noChanges': 'Nessuna modifica rilevata. Procedere comunque?',

    // Charts
    'charts.loading': 'Caricamento...',
    'charts.error': 'Impossibile caricare i dati.',
    'charts.title.contactsByStatus': 'Contatti per stato',
    'charts.title.distributionByStatus': 'Distribuzione per stato',
    'charts.title.myAssignShare': 'Quota assegnati a me',
    'charts.dataset.contacts': 'Contatti',
    'charts.status.unknown': 'Sconosciuto',

    // Extra keys (fallbacks)
    'nav.scraper': 'Scraper',
    'form.latitude': 'Latitudine',
    'form.longitude': 'Longitudine',
    'clients.addRecord': 'Aggiungi record',
    'clients.importCsv': 'Importa CSV',
    'settings.gplaces.label': 'Google Places API key (Scraper)',
    'settings.gplaces.placeholder': 'API-KEY',
    'settings.gplaces.saved': 'Key salvata',
    'settings.gplaces.notSet': 'Key non impostata',
    'settings.gplaces.remove': 'Rimuovi key',
    'settings.gplaces.save': 'Salva key',
    'settings.clients.grid': 'Griglia Clienti',
    'settings.clients.cols': 'Colonne',
    'settings.clients.rows': 'Righe',
    'settings.clients.gridHelp': 'Applica al numero di colonne e di righe per pagina nella sezione Clienti.',
    'common.copy': 'Copia',
    'common.show': 'Mostra',
    'common.hide': 'Nascondi',
    'common.saving': 'Salvataggio...',
    'common.loading': 'Caricamento...',
    'profile.sendVerification': 'Invia verifica',
    'profile.verifySent': 'Email di verifica inviata.',
    'profile.verifyError': 'Errore invio email.'
    ,
    // Charts KPI
    'charts.kpi.activePartners': 'Clienti attivi',
    // Clients/Partners page
    'clients.emptyPartners': 'Nessun partner trovato',
    'clients.errorLoadingPartners': 'Errore nel caricamento dei partner',
    'clients.partnerDetails': 'Dettagli partner',
    // My Contacts
    'myContacts.emptyAssigned': 'Nessun cliente assegnato a te',
    // Tabs
    'tabs.general': 'Generale',
    'tabs.technical': 'Tecnico',
    'tabs.economic': 'Economico',
    'tabs.project': 'Progetto',
    'tabs.map': 'Mappa',
    // Partner labels
    'partner.referent': 'Referente',
    'partner.email': 'Email',
    'partner.phone': 'Telefono',
    'partner.address': 'Indirizzo',
    'partner.website': 'Sito',
    'partner.assigned': 'Assegnato',
    'partner.status': 'Stato',
    'partner.notes': 'Note',
    'partner.domain': 'Dominio',
    'partner.domainExpiry': 'Scadenza dominio',
    'partner.hosting': 'Hosting',
    'partner.hostingExpiry': 'Scadenza hosting',
    'partner.sslExpiry': 'Scadenza SSL',
    'partner.panel': 'Pannello',
    'partner.price': 'Prezzo',
    'partner.startDate': 'Data inizio',
    'partner.endDate': 'Data fine',
    'partner.renewDate': 'Rinnovo'
  },
  en: {
    'common.search': 'Search',
    'common.new': 'New',
    'common.filters': 'Filters',
    'common.refresh': 'Refresh',
    'common.of': 'of',
    'common.prev': 'Previous',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.proceed': 'Proceed',

    'filters.errorLoading': 'Error loading filters',
    'filters.cities': 'Cities',
    'filters.searchCity': 'Search city',
    'filters.categories': 'Category',
    'filters.searchCategory': 'Search category',
    'filters.status': 'Status',
    'filters.searchStatus': 'Search status',
    'filters.clear': 'Clear',
    'filters.apply': 'Apply',

    'form.name': 'Name',
    'form.city': 'City',
    'form.category': 'Category',
    'form.assigned': 'Assigned',
    'form.status': 'Status',
    'form.follow1': 'Follow up 1',
    'form.follow2': 'Follow up 2',
    'form.site': 'Website',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.moreContacts': 'Additional contacts',
    'form.email2': 'Email 2',
    'form.phone2': 'Phone 2',
    'form.email3': 'Email 3',
    'form.phone3': 'Phone 3',
    'form.notes': 'Notes',
    'form.required': 'Required',
    'form.fillRequired': 'Fill in the required fields:',

    'details.title': 'Client details',
    'confirm.delete.title': 'Confirm deletion?',
    'confirm.delete.warning': 'This action is not reversible.',
    'confirm.site.title': 'Open external link?',
    'confirm.site.opening': 'You are about to open:',
    'confirm.save.title': 'Confirm changes?',
    'confirm.save.noChanges': 'No changes detected. Proceed anyway?',

    // Charts
    'charts.loading': 'Loading...',
    'charts.error': 'Unable to load data.',
    'charts.title.contactsByStatus': 'Contacts by status',
    'charts.title.distributionByStatus': 'Distribution by status',
    'charts.title.myAssignShare': 'My assignment share',
    'charts.dataset.contacts': 'Contacts',
    'charts.status.unknown': 'Unknown',

    // Extra keys (fallbacks)
    'nav.scraper': 'Scraper',
    'form.latitude': 'Latitude',
    'form.longitude': 'Longitude',
    'clients.addRecord': 'Add record',
    'clients.importCsv': 'Import CSV',
    'settings.gplaces.label': 'Google Places API key (Scraper)',
    'settings.gplaces.placeholder': 'API-KEY',
    'settings.gplaces.saved': 'Key saved',
    'settings.gplaces.notSet': 'Key not set',
    'settings.gplaces.remove': 'Remove key',
    'settings.gplaces.save': 'Save key',
    'settings.clients.grid': 'Clients grid',
    'settings.clients.cols': 'Columns',
    'settings.clients.rows': 'Rows',
    'settings.clients.gridHelp': 'Applies to the number of columns and rows per page in the Clients section.',
    'common.copy': 'Copy',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.saving': 'Saving...',
    'common.loading': 'Loading...',
    'profile.sendVerification': 'Send verification',
    'profile.verifySent': 'Verification email sent.',
    'profile.verifyError': 'Error sending email.'
    ,
    // Charts KPI
    'charts.kpi.activePartners': 'Active clients',
    // Clients/Partners page
    'clients.emptyPartners': 'No partners found',
    'clients.errorLoadingPartners': 'Error loading partners',
    'clients.partnerDetails': 'Partner details',
    // My Contacts
    'myContacts.emptyAssigned': 'No clients assigned to you',
    // Tabs
    'tabs.general': 'General',
    'tabs.technical': 'Technical',
    'tabs.economic': 'Economic',
    'tabs.project': 'Project',
    'tabs.map': 'Map',
    // Partner labels
    'partner.referent': 'Contact',
    'partner.email': 'Email',
    'partner.phone': 'Phone',
    'partner.address': 'Address',
    'partner.website': 'Website',
    'partner.assigned': 'Assigned',
    'partner.status': 'Status',
    'partner.notes': 'Notes',
    'partner.domain': 'Domain',
    'partner.domainExpiry': 'Domain expiry',
    'partner.hosting': 'Hosting',
    'partner.hostingExpiry': 'Hosting expiry',
    'partner.sslExpiry': 'SSL expiry',
    'partner.panel': 'Control panel',
    'partner.price': 'Price',
    'partner.startDate': 'Start date',
    'partner.endDate': 'End date',
    'partner.renewDate': 'Renewal'
  }
};

@Pipe({ name: 't', pure: false, standalone: true })
export class TranslatePipe implements PipeTransform {
  constructor(private lang: LanguageService) {}
  transform(key: string): string {
    const primary = this.lang.t(key);
    if (primary && primary !== key) return primary;
    const docLang = (typeof document !== 'undefined' && document.documentElement?.lang) || 'it';
    const l = (docLang === 'en' ? 'en' : 'it') as Lang;
    return FALLBACK[l][key] ?? key;
  }
}
